import { pgTable, text, serial, integer, timestamp, varchar } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// === TABLE DEFINITIONS ===

// User Profile (Single user for this app context, or scalable)
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  firstName: text("first_name").default("Dancer").notNull(),
  lastName: text("last_name").default("").notNull(),
  location: text("location").default("").notNull(),
});

// Song Library
export const songs = pgTable("songs", {
  id: serial("id").primaryKey(),
  publicId: varchar("public_id", { length: 6 }).notNull().unique(), // The 6-digit hidden ID
  danceName: text("dance_name").notNull(),
  songName: text("song_name").notNull(),
  rating: integer("rating").notNull().default(0), // 1-5 stars
});

// Dance Sessions
export const sessions = pgTable("sessions", {
  id: serial("id").primaryKey(),
  date: timestamp("date").notNull(),
  location: text("location").notNull(),
});

// Many-to-Many link between Sessions and Songs (Dances done in a session)
export const sessionDances = pgTable("session_dances", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").notNull(), // FK to sessions.id
  songId: integer("song_id").notNull(),       // FK to songs.id
});

// === SCHEMAS ===

export const insertUserSchema = createInsertSchema(users).omit({ id: true });
export const insertSongSchema = createInsertSchema(songs).omit({ id: true }); // publicId should be generated by backend
export const insertSessionSchema = createInsertSchema(sessions).omit({ id: true });
export const insertSessionDanceSchema = createInsertSchema(sessionDances).omit({ id: true });

// === EXPLICIT TYPES ===

export type User = typeof users.$inferSelect;
export type InsertUser = z.infer<typeof insertUserSchema>;

export type Song = typeof songs.$inferSelect;
export type InsertSong = z.infer<typeof insertSongSchema>;

export type Session = typeof sessions.$inferSelect;
export type InsertSession = z.infer<typeof insertSessionSchema>;

export type SessionDance = typeof sessionDances.$inferSelect;
export type InsertSessionDance = z.infer<typeof insertSessionDanceSchema>;

// Request Types
export type CreateSongRequest = Omit<InsertSong, 'publicId'>; // Backend generates publicId
export type UpdateSongRequest = Partial<Omit<InsertSong, 'publicId'>>; // ID immutable

export type CreateSessionRequest = InsertSession & {
  danceIds: number[]; // Array of song IDs to link
};
export type UpdateSessionRequest = Partial<InsertSession> & {
  danceIds?: number[]; // Optional update to dance list
};

// Response Types
export type SongResponse = Song;
export type SessionResponse = Session & {
  dances: Song[];
};
export type StatsResponse = {
  totalDances: number;
  longestStreak: number;
  totalDaysDancing: number;
  uniqueLocations: number;
  mostFrequentLocation: string;
  mostFrequentLocationCount: number;
  mostFrequentDance: string;
  mostFrequentDanceCount: number;
};
